# Generated by Django 4.2.24 on 2025-09-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='crs',
            field=models.CharField(blank=True, help_text='Coordinate Reference System', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='geoserver_layer_name',
            field=models.CharField(blank=True, help_text='Layer name in GeoServer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='geoserver_workspace',
            field=models.CharField(blank=True, help_text='GeoServer workspace', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='gis_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('processed', 'Processed'), ('published', 'Published to GeoServer'), ('error', 'Processing Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='is_spatial',
            field=models.BooleanField(default=False, help_text='Whether this is a spatial/GIS file'),
        ),
        migrations.AddField(
            model_name='file',
            name='processing_log',
            field=models.TextField(blank=True, help_text='Log of processing steps'),
        ),
        migrations.AddField(
            model_name='file',
            name='spatial_extent',
            field=models.TextField(blank=True, help_text='Spatial extent of the data (JSON)', null=True),
        ),
    ]
