# Generated by Django 4.2.24 on 2025-09-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_file_crs_file_geoserver_layer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='chroma_id',
            field=models.CharField(blank=True, help_text='Reference ID in ChromaDB vector database', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time embedding was updated', null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='chroma_id',
            field=models.CharField(blank=True, help_text='Reference ID in ChromaDB vector database', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time embedding was updated', null=True),
        ),
    ]
