# Generated by Django 4.2.24 on 2025-09-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_file_chroma_id_file_embedding_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='geoserver_datastore_name',
            field=models.CharField(blank=True, help_text='Datastore/Coverage store name in GeoServer', max_length=255, null=True),
        ),
    ]
