# Generated by Django 4.2.24 on 2025-09-21 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0004_file_geoserver_datastore_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the custom map', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the map', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this map is visible to everyone')),
                ('geoserver_layer_group_name', models.CharField(help_text='Unique Layer Group name in GeoServer for this composite map', max_length=255, unique=True)),
                ('geoserver_workspace', models.CharField(default='adma_geo', help_text='GeoServer workspace containing the layer group', max_length=100)),
                ('center_lat', models.FloatField(blank=True, help_text='Map center latitude', null=True)),
                ('center_lng', models.FloatField(blank=True, help_text='Map center longitude', null=True)),
                ('zoom_level', models.IntegerField(default=10, help_text='Default zoom level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_order', models.IntegerField(default=0, help_text='Display order in the map (lower numbers appear on top)')),
                ('opacity', models.FloatField(default=1.0, help_text='Layer opacity (0.0 = transparent, 1.0 = opaque)')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this layer is visible')),
                ('style_name', models.CharField(blank=True, help_text='GeoServer style name for this layer', max_length=255, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_memberships', to='filemanager.file')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_layers', to='filemanager.map')),
            ],
            options={
                'ordering': ['layer_order', 'added_at'],
                'unique_together': {('map', 'file')},
            },
        ),
    ]
