# Generated by Django 4.2.24 on 2025-09-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0005_map_maplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='bbox_max_lat',
            field=models.FloatField(blank=True, help_text='Maximum latitude of all files', null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='bbox_max_lng',
            field=models.FloatField(blank=True, help_text='Maximum longitude of all files', null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='bbox_min_lat',
            field=models.FloatField(blank=True, help_text='Minimum latitude of all files', null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='bbox_min_lng',
            field=models.FloatField(blank=True, help_text='Minimum longitude of all files', null=True),
        ),
    ]
