# Generated by Django 4.2.24 on 2025-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0006_map_bbox_max_lat_map_bbox_max_lng_map_bbox_min_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='chroma_id',
            field=models.CharField(blank=True, help_text='ChromaDB collection ID for search', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time embeddings were updated', null=True),
        ),
    ]
