# Generated by Django 4.2.24 on 2025-09-22 05:42

from django.db import migrations, models
import filemanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0007_map_chroma_id_map_embedding_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=500, upload_to=filemanager.models.get_upload_path),
        ),
    ]
