# Generated by Django 4.2.24 on 2025-09-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0008_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deletion_in_progress',
            field=models.BooleanField(default=False, help_text='True when file is being deleted asynchronously'),
        ),
        migrations.AddField(
            model_name='folder',
            name='deletion_in_progress',
            field=models.BooleanField(default=False, help_text='True when folder is being deleted asynchronously'),
        ),
    ]
