# Generated by Django 4.2.24 on 2025-09-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0009_add_deletion_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='deletion_in_progress',
            field=models.BooleanField(default=False, help_text='True when map is being deleted asynchronously'),
        ),
    ]
