# Generated by Django 4.2.24 on 2025-09-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0010_add_map_deletion_in_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='chroma_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='embedding_updated_at',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='chroma_id',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='embedding_updated_at',
        ),
        migrations.RemoveField(
            model_name='map',
            name='chroma_id',
        ),
        migrations.RemoveField(
            model_name='map',
            name='embedding_updated_at',
        ),
    ]
