# Generated by Django 4.2.30 on 2026-08-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0013_add_third_party_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='cached_total_file_count',
            field=models.IntegerField(default=0, help_text='Precomputed total file count in this folder and subfolders'),
        ),
        migrations.AddField(
            model_name='folder',
            name='cached_total_size',
            field=models.BigIntegerField(default=0, help_text='Precomputed total size of files in this folder and subfolders'),
        ),
    ]
