# Generated by Django 4.2.29 on 2026-03-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0015_chatsession_agentmessage_chat_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='is_streaming',
            field=models.BooleanField(default=False, help_text='True while the agent is still generating this message'),
        ),
    ]
