# Generated by Django 4.2.29 on 2026-04-16 20:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0016_agentmessage_is_streaming'),
    ]

    operations = [
        migrations.CreateModel(
            name='JohnDeereSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jd_subscription_id', models.CharField(max_length=128, unique=True)),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('event_type_ids', models.JSONField(default=list)),
                ('client_endpoint', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. When True, file is hidden from normal listings.'),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. When True, folder is hidden from normal listings.'),
        ),
        migrations.CreateModel(
            name='JohnDeereWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jd_event_id', models.CharField(max_length=128, unique=True)),
                ('event_type_id', models.CharField(db_index=True, max_length=64)),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('target_resource_uri', models.URLField(blank=True, max_length=1000, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped_duplicate', 'Skipped (duplicate)'), ('skipped_unknown_type', 'Skipped (unknown type)')], db_index=True, default='pending', max_length=32)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('related_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filemanager.file')),
                ('related_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filemanager.folder')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
